---

# Play to install and configure postgreSQL

- name: Installing and setting up postgreSQL
  hosts: all
  become: yes
  vars_files:
    - vars/default.yml
  tasks:

  - name: Copy Script from local to remote
    tags: postgres
    copy:
      src: postgresql.sh
      dest: /home/{{ created_username }}/
      owner: "{{ created_username }}"
      group: "{{ created_username }}"
      mode: u=rwx,g=rw,o=r

  - name: Copy postgresql.conf file for remote access
    tags: postgres
    copy:
      src: files/postgres.conf
      dest: /etc/postgresql/15/main/postgresql.conf
      owner: postgres
      group: postgres
      mode: 0644
      backup: yes 
    notify:
      restart postgresql

  - name: Copy pg_hba.conf file for remote access
    tags: postgres
    copy:
      src: files/pg_hba.conf
      dest: /etc/postgresql/15/main/pg_hba.conf
      owner: postgres                
      group: postgres                
      mode: 0640
      backup: yes
    notify:
      restart postgresql

  - name: Execute Script
    tags: postgres
    command: sh /home/{{ created_username }}/postgresql.sh
 
  handlers:
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
