---


# Play to update repository
- hosts: all
  become: true 
  gather_facts: False
  
  pre_tasks:

  - name: Install aptitude
    tags: always
    apt:
        name: aptitude
        state: latest
        update_cache: true

  - name: Upgrade repository
    tags: always
    apt:
      upgrade: dist


# Play to create user and the connection credentials 
- hosts: all
  become: true
  gather_facts: False
  vars_files:
     - vars/default.yml
  tasks: 

  - name: Setup passwordless sudo for admin group
    tags: user
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%admin'
      line: '%admin ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  - name: Create an ansible user to connect to the control node
    tags: user
    user:
      name: "{{ created_username }}"
      state: present
      groups: admin
      append: yes
      create_home: true
      shell: /bin/bash
  
  - name: Add ssh key for ansible user
    tags: user
    authorized_key:
      user: "{{ created_username }}"
      state: present
      key: "{{ lookup('file', '/home/vagrant/.ssh/ansible.pub') }}"

  - name: Disable password authentication for root
    tags: user
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin prohibit-password'

  - name: Add ssh key for remote connection
    tags: user
    authorized_key:
      user: "{{ created_username }}"
      state: present
      key: "{{ lookup('file', '/home/vagrant/.ssh/id_ed25519.pub') }}"


# Play to install required system packages like git, ufw, and set timezone
- hosts: all
  become: yes
  vars_files:
     - vars/default.yml 
  tasks:

  - name: Update apt and install required system packages
    tags: setup
    apt:
      pkg:
        - curl
        - git
        - ufw
        - wget
      state: latest
      update_cache: true

  - name: Allow SSH connection on the server
    tags: setup
    ufw:
      rule: allow
      name: OpenSSH

  - name: Enable and deny by default
    tags: setup
    ufw:
      state: enabled
      default: deny
  
  - name: Allow all access to tcp port 80
    tags: setup
    ufw:
      rule: allow
      port: "{{ http_port }}"
      proto: tcp

  - name: Allow all access to https
    tags: setup
    ufw:
      rule: allow
      port: "{{ https_port }}"
      proto: tcp

  - name: Set timezone on server
    tags: setup
    timezone:
      name: "{{ timezone }}"


# Play to Install apache and php packages
- hosts: all
  become: true
  tasks:

  - name: Installing Apache and PHP packages and dependencies
    tags: apache,php
    apt:
       name: "{{ item }}" 
       update_cache: yes 
       state: latest
    loop:
      - apache2
      - apt-transport-https
      - gnupg2
      - ca-certificates
      - software-properties-common
 
  - name: add a ppa:ondrej/php repository to APT
    tags: apache,php
    apt_repository:
      validate_certs: no
      repo: 'ppa:ondrej/php'
      state: present
      update_cache: yes

  - name: install php libraries
    tags: apache,php
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    loop:
      - php
      - php-mysql
      - libapache2-mod-php
      - python3-pymysql
      - php-common
      - php-xml 
      - php-gd
      - php-tokenizer
      - php-mbstring
      - php-json
      - php-zip
      - unzip
      - php-bcmath
      - php-curl
      - php-intl
      - php-soap
      - php-xdebug
      - php-imagick

#Certbot for TLS/SSL  
  - name: Install certbot for TLS/SSL
    tags: apache,php
    apt:
      name: certbot
      state: present
      update_cache: yes
    

# Play to edit the php.ini file
- hosts: all
  become: yes
  gather_facts: False
  tasks:

  - name: ensure cgi.fix_pathinfo is set to 0
    tags: config
    lineinfile:
      dest: /etc/php/8.1/apache2/php.ini
      regexp: '^(.*)cgi.fix_pathinfo=' 
      line: cgi.fix_pathinfo=0
    notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded


# Play to install and Secure MySQL server and create database and user
- name: Install MySQL server, Secure it, and create user and db
  hosts: all
  become: true
  vars_files:
     - vars/default.yml
  tasks:

  - name: Install MySQL and Dependencies
    tags: mysql
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
    become: yes

  - name: start and enable mysql service
    tags: mysql
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Copy .my.cnf file with root password credentials
    no_log: true
    tags: mysql
    template:
      src: "files/client.my.cnf.j2"
      dest: "/root/.my.cnf"
      owner: root
      group: root
      mode: 0600
    register: mycnf_is_installed
    failed_when: false

  - name: secure mysql installation
    tags: mysql
    become: yes
    expect:
      command: mysql_secure_installation
      responses:
        'Enter current password for root': ''
        'Set root password': 'n'
        'Remove anonymous users': 'y'
        'Disallow root login remotely': 'y'
        'Remove test database': 'y'
        'Reload privilege tables now': 'y'
      timeout: 5
    register: secure_mysql
    failed_when: "'... Failed!' in secure_mysql.stdout_lines"

  - name: Create a new database for the project
    tags: mysql
    mysql_db:
      name: "{{ db_name }}"
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
    when: mycnf_is_installed is succeeded
    failed_when: false
    no_log: true

  - name: Create database user with all database privileges
    tags: mysql
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: '*.*:ALL'
      state: present
    when: mycnf_is_installed is succeeded
    failed_when: false
    no_log: true

  - name: Remove /root/.my.cnf
    tags: mysql
    file:
      path: /root/.my.cnf
      state: absent


# Play to install composer
- name: Install composer package
  hosts: all
  become: true
  tasks:

  - name: Download composer file with check (sha256)
    tags: composer
    get_url:
      url: https://getcomposer.org/download/latest-stable/composer.phar
      dest: /usr/local/bin/composer.phar
      checksum:
        sha256:c252c2a2219956f88089ffc242b42c8cb9300a368fd3890d63940e4fc9652345 
 
  - name: rename composer.phar to composer
    tags: composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    args:
      creates: /usr/local/bin/composer

  - name: make composer executable
    tags: composer
    file: 
      path: /usr/local/bin/composer
      mode: a+x
      state: file


# Play to set app root directory and clone repo
- name: Setting up Apache document root configuration
  hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  - name: Check if app directory already exists
    tags: git
    stat:
      path: "/var/www/html/{{ vhost_name }}"
    register: app_present

  - name: Setting app root directory and ownership for git cloning
    tags: git
    file:
      path: "/var/www/html/"
      state: directory
      owner: "{{ created_username }}"
      mode: u=rwX,g=rX,o=rX
    become: true
    when: not app_present.stat.exists

  - name: download latest code from github to app directory
    tags: git
    git:
      repo: https://github.com/f1amy/laravel-realworld-example-app.git
      dest: "/var/www/html/{{ vhost_name }}"
      force: yes
      accept_hostkey: yes
    when: not app_present.stat.exists

  - name: set up the .env file for laravel project
    tags: git
    template:
      src: "files/env.j2"
      dest: /var/www/html/{{ vhost_name }}/.env
    when: not app_present.stat.exists

  - name: Set the permission and ownership for project
    tags: git
    file:
      path: /var/www/html/{{ vhost_name }}
      state: directory
      recurse: yes
      owner: "{{ created_username }}"
      group: www-data
    become: true
    when: not app_present.stat.exists

  - name: Change permission for app directory recursively
    tags: git
    file:
      path: /var/www/html/{{ vhost_name }}
      mode: u=rwX,g=rX,o=rX
      recurse: yes
    become: true
    when: not app_present.stat.exists

  - name: Change permission for app directory storage recursively
    tags: git
    file:
      path: /var/www/html/{{ vhost_name }}/storage
      mode: u=rwX,g=rX,o=rX
      recurse: yes
    become: true
    when: not app_present.stat.exists

  - name: Change permission for app's bootstrap/cache directory recursively
    tags: git
    file:
      path: /var/www/html/{{ vhost_name }}
      mode: u=rwX,g=rX,o=rX
      recurse: yes
    become: true
    when: not app_present.stat.exists


# Play to install laravel with composer and setup virtual host
- name: Composer install app and set up virtual host
  hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  - name: composer install app
    tags: laravel
    command: composer install
    become: yes
    become_user: "{{ created_username }}"
    args:
      chdir: /var/www/html/{{ vhost_name }}
    when: not app_present.stat.exists 

#migrating and seeding the database created. 
  - name: Run artisan migrate for the database
    tags: laravel
    shell: php /var/www/html/{{ vhost_name }}/artisan migrate --seed
    become_user: "{{ created_username }}"
    become: yes 
    when: not app_present.stat.exists

  - name: set ownership of app to www-data:www-data
    tags: laravel
    file:
      path: /var/www/html/{{ vhost_name }}
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
    become: true
    when: not app_present.stat.exists

  - name: Change app directory permission
    tags: laravel
    file:
      path: /var/www/html/{{ vhost_name }}/storage
      mode: u=rwX,g=rX,o=rX
      recurse: yes
    become: true
    when: not app_present.stat.exists      

# Play to set Apache's config file and virtual hosting of app
- name: Setting Apache's config file
  hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:
  
  - name: Create an apache virtual host config file for the project
    tags: virtualhost
    template: 
      src: "files/apache.conf.j2"
      dest: /etc/apache2/sites-available/{{ http_conf }}
    become: true
    when: app_present.stat.exists
    notify: reload apache 

  - name: enable apache virtualhost
    tags: virtualhost
    shell: /usr/sbin/a2ensite {{ http_conf }}
    when: app_present.stat.exists
    notify: reload apache

  - name: disable apache default site
    tags: virtualhost
    shell: /usr/sbin/a2dissite 000-default.conf
    when: app_present.stat.exists
    notify: reload apache
   
  - name: rewrite apache module
    tags: virtualhost
    shell: /usr/sbin/a2enmod rewrite
    when: app_present.stat.exists
    become: true
    notify: reload apache

  handlers:
    - name: reload apache
      service:
        name: apache2
        state: reloaded


