---
mysql_root_password: "root"
db_user: "miniproject"
db_password: "miniproject"
db_name: "miniproject"

#app_user: "funmilayo"
vhost_name: lavarel
http_host: "64.227.35.94"
#http_conf: "your_domain.conf"
created_username: "funmilayo"
http_port: "80"
https_port: "443"
timezone: "Africa/Lagos"
#disable_default: true

